# Generated by Django 5.1.4 on 2025-01-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medico_paciente_remove_texto_categoria_agendamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelamento', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.cancelamento'),
        ),
    ]
