# Generated by Django 5.1.4 on 2025-01-23 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_cancelamento_agendamento_cancelamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_exclusao', models.DateField(auto_now_add=True)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.paciente')),
            ],
        ),
    ]
